kind: pipeline
type: docker
name: freeday-doc-deploy

steps:
# dependencies
- name: dependencies
  image: node
  pull: if-not-exists
  commands:
  - npm i
  when:
    branch:
    - master
    - dev
# linters
- name: lint
  image: node
  pull: if-not-exists
  depends_on:
  - dependencies
  commands:
  - npm run lint
  when:
    branch:
    - master
    - dev
# deployment
- name: deploy
  image: node
  pull: if-not-exists
  depends_on:
  - lint
  commands:
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - echo "$GITHUB_KEY" > "$HOME/.ssh/id_rsa"
    - chmod 600 $HOME/.ssh/id_rsa
    - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER:
      from_secret: github_user
    GITHUB_KEY:
      from_secret: github_key
  when:
    branch:
    - master
