kind: pipeline
type: docker
name: freeday-doc-deploy

trigger:
  branch:
    - master

steps:
- name: deploy
  image: node
  commands:
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - echo "$GITHUB_KEY" > "$HOME/.ssh/id_rsa"
    - chmod 600 $HOME/.ssh/id_rsa
    - cd deploy
    - npm i
    - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER:
      from_secret: github_user
    GITHUB_KEY:
      from_secret: github_key
