kind: pipeline
type: docker
name: freeday-doc-ci

trigger:
  branch:
  - dev
  event:
  - push
  - pull_request

steps:
- name: install
  image: node
  pull: if-not-exists
  commands:
  - npm ci
- name: lint
  image: node
  pull: if-not-exists
  depends_on:
  - install
  commands:
  - npm run lint

---
kind: pipeline
type: docker
name: freeday-doc-deploy

trigger:
  event:
  - tag

steps:
- name: deploy
  image: node
  pull: if-not-exists
  commands:
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - echo "$GITHUB_KEY" > "$HOME/.ssh/id_rsa"
    - chmod 600 $HOME/.ssh/id_rsa
    - npm i
    - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER:
      from_secret: github_user
    GITHUB_KEY:
      from_secret: github_key
